function kdx=Kd_x(g,w,tau)
kdx=exp(1).^(g.*tau).*w.^(-1).*(imag(M(g+sqrt(-1).*w)).^2+real(M(g+sqrt(-1).*w)).^2) ...
  .^(-1).*(imag(M(g+sqrt(-1).*w)).*((g+(-1).*w).*(g+w).*cos(tau.*w)+(-2).*g.* ...
  w.*sin(tau.*w))+real(M(g+sqrt(-1).*w)).*((-2).*g.*w.*cos(tau.*w)+((-1).*g.^2+ ...
  w.^2).*sin(tau.*w)));
end