function kpx=Kp_x(g,w,tau)
kpx=exp(1).^(g.*tau).*w.^(-1).*(g.^2+w.^2).*(imag(M(g+sqrt(-1).*w)).^2+real(M(g+ ...
  sqrt(-1).*w)).^2).^(-1).*(real(M(g+sqrt(-1).*w)).*(w.*cos(tau.*w)+g.*sin(tau.* ...
  w))+imag(M(g+sqrt(-1).*w)).*((-1).*g.*cos(tau.*w)+w.*sin(tau.*w)));
end