kpx=exp(1).^(g.*tau).*w.^(-1).*(g.^2+w.^2).*(Imm(g+sqrt(-1).*w).^2+Rm(g+ ...
  sqrt(-1).*w).^2).^(-1).*(Rm(g+sqrt(-1).*w).*(w.*cos(tau.*w)+g.*sin(tau.* ...
  w))+Imm(g+sqrt(-1).*w).*((-1).*g.*cos(tau.*w)+w.*sin(tau.*w)));
kdx=exp(1).^(g.*tau).*w.^(-1).*(Imm(g+sqrt(-1).*w).^2+Rm(g+sqrt(-1).*w).^2) ...
  .^(-1).*(Imm(g+sqrt(-1).*w).*((g+(-1).*w).*(g+w).*cos(tau.*w)+(-2).*g.* ...
  w.*sin(tau.*w))+Rm(g+sqrt(-1).*w).*((-2).*g.*w.*cos(tau.*w)+((-1).*g.^2+ ...
  w.^2).*sin(tau.*w)));
